/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    Barcode: typeof import('./src/components/Barcode.vue')['default']
    CultureCreate: typeof import('./src/components/CultureCreate.vue')['default']
    CultureDetails: typeof import('./src/components/CultureDetails.vue')['default']
    Cultures: typeof import('./src/components/Cultures.vue')['default']
    CultureSearch: typeof import('./src/components/CultureSearch.vue')['default']
    CulturesTable: typeof import('./src/components/CulturesTable.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    FavoriteNotes: typeof import('./src/components/FavoriteNotes.vue')['default']
    Favorites: typeof import('./src/components/Favorites.vue')['default']
    GraphView: typeof import('./src/components/GraphView.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu.vue')['default']
    Notes: typeof import('./src/components/Notes.vue')['default']
    QrcodeStream: typeof import('./src/components/QrcodeStream.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shroomy: typeof import('./src/components/Shroomy.vue')['default']
    Statistic: typeof import('./src/components/Statistic.vue')['default']
    TagCloud: typeof import('./src/components/TagCloud.vue')['default']
    TagSearch: typeof import('./src/components/TagSearch.vue')['default']
  }
}
